apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-frontend
  namespace: workshop-frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: workshop-frontend
  template:
    metadata:
      labels:
        app: workshop-frontend
    spec:
      containers:
        - name: workshop-frontend
          image: ghcr.io/akatruk/workshop-frontend:e979c14a40d71d97719c7ea5d2f7314f23eaefcc
          ports:
            - containerPort: 3000  
---

apiVersion: v1
kind: Service
metadata:
  name: workshop-frontend-service
spec:
  selector:
    app: workshop-frontend
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 3000  # The port your Node.js app is listening on
  type: LoadBalancer  # Use "LoadBalancer" for cloud environments like AWS, GCP, Azure
