name: CI/CD Pipeline on main branch

on:
  push:
    branches:
      - main

jobs:      
  build-and-push-production:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository_owner }}/workshop-frontend:$GITHUB_SHA -f .devops/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/workshop-frontend:$GITHUB_SHA

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Generate kubectl config
        run: |
          aws eks update-kubeconfig --name eks-prod --region us-east-1

      - name: Apply ArgoCD Manifests
        run: |
          kubectl apply -f devops/argocd/argocd-prod.yml --validate=false